In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
df = pd.read_csv("../data/cleaned_superstore.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656

In [3]:
engine = create_engine("sqlite:///superstore.db")

df.to_sql(
    "superstore",
    engine,
    if_exists="replace",
    index=False
)

print("Database Created Successfully")

Database Created Successfully

In [4]:
query = """
SELECT *
FROM superstore
LIMIT 5;
"""

pd.read_sql(query, engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656

In [5]:
query = """
SELECT
    Category,
    Sales
FROM superstore
LIMIT 10;
"""

pd.read_sql(query, engine)

          Category    Sales
0        Furniture  261.960
1  Office Supplies   14.620
2  Office Supplies   22.368
3        Furniture   48.860
4  Office Supplies    7.280
5  Office Supplies   18.504
6  Office Supplies  114.900
7  Office Supplies   15.552
8  Office Supplies  407.976
9  Office Supplies   68.810

In [6]:
query = """
SELECT *
FROM superstore
WHERE Sales > 500;
"""

pd.read_sql(query, engine)

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [7]:
query = """
SELECT
    Product_Name,
    Sales
FROM superstore
ORDER BY Sales DESC
LIMIT 10;
"""

In [8]:
query = """
SELECT
    [Product Name],
    SUM(Sales) AS TotalSales
FROM superstore
GROUP BY [Product Name]
ORDER BY TotalSales DESC
LIMIT 5;
"""

pd.read_sql(query, engine)

                                       Product Name  TotalSales
0                        KI Adjustable-Height Table    4036.761
1   Global Wood Trimmed Manager's Task Chair, Khaki    3621.004
2        Situations Contoured Folding Chairs, 4/Set    2959.866
3         Global High-Back Leather Tilter, Burgundy    2841.069
4  Nortel Meridian M3904 Professional Digital phone    2802.618

In [9]:
query = """
SELECT
    [Customer Name],
    SUM(Sales) AS TotalSales
FROM superstore
GROUP BY [Customer Name]
ORDER BY TotalSales DESC
LIMIT 5;
"""

pd.read_sql(query, engine)

     Customer Name  TotalSales
0       Paul Prost    4196.928
1  Laura Armstrong    3751.798
2     Ken Lonsdale    3371.691
3         John Lee    3338.352
4    William Brown    3131.974

In [10]:
query = """
SELECT
    Category,
    SUM(Sales) AS TotalSales
FROM superstore
GROUP BY Category;
"""

pd.read_sql(query, engine)

          Category   TotalSales
0        Furniture  247877.6984
1  Office Supplies  343425.0040
2       Technology  228415.3530

In [11]:
query = """
SELECT
    Region,
    SUM(Profit) AS TotalProfit
FROM superstore
GROUP BY Region;
"""

pd.read_sql(query, engine)

    Region  TotalProfit
0  Central    2789.1815
1     East   28025.6875
2    South   22150.0444
3     West   45885.5132

In [12]:
query = """
SELECT *
FROM superstore
WHERE Sales >
(
    SELECT AVG(Sales)
    FROM superstore
);
"""

pd.read_sql(query, engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.900,5,0.0,34.4700
2,14,CA-2016-161389,2016-12-05,2016-12-10,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,...,98103,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.976,3,0.2,132.5922
3,20,CA-2014-143336,2014-08-27,2014-09-01,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.480,3,0.2,16.0110
4,30,US-2015-150630,2015-09-17,2015-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-FU-10004848,Furniture,Furnishings,"Howard Miller 13-3/4"" Diameter Brushed Chrome ...",124.200,3,0.2,15.5250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2753,9980,US-2016-103674,2016-12-06,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.472,14,0.2,153.1152
2754,9984,US-2016-157728,2016-09-22,2016-09-28,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,49505,Central,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.980,2,0.0,27.4344
2755,9989,CA-2017-163629,2017-11-17,2017-11-21,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.100,5,0.0,55.6470
2756,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
2757,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [13]:
query = """
WITH CategorySales AS
(
    SELECT
        Category,
        SUM(Sales) AS TotalSales
    FROM superstore
    GROUP BY Category
)

SELECT *
FROM CategorySales;
"""

pd.read_sql(query, engine)

          Category   TotalSales
0        Furniture  247877.6984
1  Office Supplies  343425.0040
2       Technology  228415.3530

In [14]:
query = """
SELECT
    [Customer Name],
    Sales,
    RANK() OVER
    (
        ORDER BY Sales DESC
    ) AS SalesRank
FROM superstore;
"""

pd.read_sql(query, engine)

         Customer Name    Sales  SalesRank
0      Cynthia Arntzen  498.260          1
1         Tamara Chand  498.000          2
2        Justin Ritter  497.940          3
3      Muhammed Yedwab  497.610          4
4        Bruce Stewart  496.860          5
...                ...      ...        ...
8822     Henry Goldwyn    0.876       8823
8823     Jas O'Carroll    0.852       8824
8824       Ken Brennan    0.836       8825
8825    Roland Schwarz    0.556       8826
8826  Zuschuss Carroll    0.444       8827

[8827 rows x 3 columns]